In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("employees_dataset.csv")
df["Tax"]=df.apply(lambda x:"10%" if x["Salary"]>50000 else "5%", axis=1)
df.assign(newincome=df["Salary"]*1.10)
df.head(15)

,EmployeeID,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax
0,1,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%
1,2,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%
2,3,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%
3,4,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%
4,5,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%
5,6,Qasim Iqbal,24,Female,Karachi,Finance,105861.0,2016-04-28,10,1.4,10%
6,7,Javed Aslam,30,Male,Multan,Operations,84921.0,2025-05-23,1,4.7,10%
7,8,Saima Raza,54,Male,Peshawar,HR,151178.0,2021-05-21,5,3.8,10%
8,9,Zara Ahmed,34,Female,Karachi,Operations,135162.0,2019-02-07,7,4.7,10%
9,10,Nida Qureshi,45,Female,Rawalpindi,HR,99436.0,2017-04-24,9,3.2,10%
10,11,Rashid Riaz,45,Male,Multan,Finance,66262.0,2023-08-03,3,4.0,10%
11,12,Bilqees Raza,47,Male,Mingora,IT,130864.0,2021-10-15,5,3.1,10%
12,13,Fatima Soomro,37,Female,Multan,IT,106939.0,2021-03-15,5,1.0,10%
13,14,Mudassar Raza,52,Male,Lahore,Marketing,197496.0,2023-10-07,3,1.6,10%
14,15,Owais Abbasi,20,Female,Mingora,Operations,158085.0,2015-02-12,11,4.5,10%

In [4]:
df.rename(columns={"Salary":"Income"}, inplace=True)
df.head(10)
df.rename(columns={"Income":"Salary"}, inplace=True)
df

,EmployeeID,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax
0,1,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%
1,2,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%
2,3,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%
3,4,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%
4,5,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Irfan Raza,39,Male,Karachi,Sales,115032.0,2015-05-12,11,2.5,10%
96,97,Rabia Abbasi,46,Male,Mingora,HR,74560.0,2017-02-20,9,4.5,10%
97,98,Lubna Awan,29,Female,Peshawar,R&D,197222.0,2019-08-09,7,3.7,10%
98,99,Umar Soomro,30,Female,Lahore,R&D,120587.0,2024-05-21,2,4.8,10%
99,100,Javed Shah,32,Female,Faisalabad,R&D,57958.0,2018-07-19,8,2.4,10%

In [5]:

df.sort_values(["Salary"])
df["ranking"]=df["Salary"].rank(ascending=False,method="dense")
df.head()

,EmployeeID,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax,ranking
0,1,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%,74.0
1,2,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%,65.0
2,3,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%,94.0
3,4,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%,83.0
4,5,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%,17.0

In [13]:
new_order=[col for col in df.columns if col!="EmployeeID"]+["EmployeeID"]
print(new_order)

['Name', 'Age', 'Gender', 'City', 'Department', 'Salary', 'JoinDate', 'ExperienceYears', 'PerformanceScore', 'Tax', 'ranking', 'EmployeeID']

In [21]:
head=df.loc[1:10]
df.iloc[0:10]

,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax,ranking
EmployeeID,,,,,,,,,,,
1,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%,74.0
2,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%,65.0
3,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%,94.0
4,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%,83.0
5,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%,17.0
6,Qasim Iqbal,24,Female,Karachi,Finance,105861.0,2016-04-28,10,1.4,10%,53.0
7,Javed Aslam,30,Male,Multan,Operations,84921.0,2025-05-23,1,4.7,10%,68.0
8,Saima Raza,54,Male,Peshawar,HR,151178.0,2021-05-21,5,3.8,10%,29.0
9,Zara Ahmed,34,Female,Karachi,Operations,135162.0,2019-02-07,7,4.7,10%,41.0
10,Nida Qureshi,45,Female,Rawalpindi,HR,99436.0,2017-04-24,9,3.2,10%,56.0

In [ ]:
head.to_csv("head.csv",index=False)

In [ ]:
pd.read_csv("head.csv")

,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax,ranking
0,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%,74.0
1,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%,65.0
2,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%,94.0
3,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%,83.0
4,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%,17.0
5,Qasim Iqbal,24,Female,Karachi,Finance,105861.0,2016-04-28,10,1.4,10%,53.0
6,Javed Aslam,30,Male,Multan,Operations,84921.0,2025-05-23,1,4.7,10%,68.0
7,Saima Raza,54,Male,Peshawar,HR,151178.0,2021-05-21,5,3.8,10%,29.0
8,Zara Ahmed,34,Female,Karachi,Operations,135162.0,2019-02-07,7,4.7,10%,41.0
9,Nida Qureshi,45,Female,Rawalpindi,HR,99436.0,2017-04-24,9,3.2,10%,56.0

In [32]:
head.groupby("Name")["Salary"].median()
df

,Name,Age,Gender,City,Department,Salary,JoinDate,ExperienceYears,PerformanceScore,Tax,ranking
EmployeeID,,,,,,,,,,,
1,Fatima Khan,37,Male,Peshawar,Finance,66579.0,2016-11-24,10,4.6,10%,74.0
2,Rashid Riaz,22,Male,Karachi,IT,87314.0,2018-09-20,8,1.1,10%,65.0
3,Owais Riaz,34,Male,Rawalpindi,Marketing,31703.0,2017-12-14,9,2.4,5%,94.0
4,Nida Chaudhary,26,Male,Lahore,Support,55353.0,2020-06-20,6,2.1,10%,83.0
5,Javed Soomro,27,Female,Faisalabad,IT,174714.0,2019-11-20,7,4.5,10%,17.0
...,...,...,...,...,...,...,...,...,...,...,...
96,Irfan Raza,39,Male,Karachi,Sales,115032.0,2015-05-12,11,2.5,10%,48.0
97,Rabia Abbasi,46,Male,Mingora,HR,74560.0,2017-02-20,9,4.5,10%,72.0
98,Lubna Awan,29,Female,Peshawar,R&D,197222.0,2019-08-09,7,3.7,10%,2.0
99,Umar Soomro,30,Female,Lahore,R&D,120587.0,2024-05-21,2,4.8,10%,46.0
100,Javed Shah,32,Female,Faisalabad,R&D,57958.0,2018-07-19,8,2.4,10%,80.0

In [37]:
rawdata=df.head(10)
rawdata.groupby("Name")["Salary"].mean()

Name
Fatima Khan        66579.0
Javed Aslam        84921.0
Javed Soomro      174714.0
Nida Chaudhary     55353.0
Nida Qureshi       99436.0
Owais Riaz         31703.0
Qasim Iqbal       105861.0
Rashid Riaz        87314.0
Saima Raza        151178.0
Zara Ahmed        135162.0
Name: Salary, dtype: float64

In [38]:
rawdata.groupby("Department")["Salary"].mean()

Department
Finance        86220.0
HR            125307.0
IT            131014.0
Marketing      31703.0
Operations    110041.5
Support        55353.0
Name: Salary, dtype: float64

In [41]:
df.groupby("City").agg(
    {
    "Salary":"max",
    "Gender":"min"
    }
)

              Salary  Gender
City
Faisalabad  183112.0  Female
Islamabad   185987.0  Female
Karachi     182701.0  Female
Lahore      197496.0  Female
Mingora     158085.0  Female
Multan      174281.0  Female
Peshawar    197222.0  Female
Quetta      175691.0  Female
Rawalpindi  193120.0  Female
Sialkot     191457.0  Female